### ISSUE TITLE
New error when running econ

### ISSUE THREAD

**Issue by nickwg03** [NREL/rex#78]
**Bug Description**
**Note** this is high priority if it is not just an error in our config. We have to have results out by COB Thursday (2/25), so this will be a blocker if it is not resolved.

I'm getting a new error when running Econ, but when running (for example) 5 workers, one of the workers does not fail while the others fail almost immediately. See below for error.

**Full Traceback**
```
Error running reV Econ CLI
Traceback (most recent call last):
  File "/home/ngrue/.conda-envs/rev/lib/python3.8/site-packages/reV/econ/cli_econ.py", line 580, in <module>
    main(obj={})
  File "/home/ngrue/.conda-envs/rev/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ngrue/.conda-envs/rev/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ngrue/.conda-envs/rev/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ngrue/.conda-envs/rev/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ngrue/.conda-envs/rev/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ngrue/.conda-envs/rev/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ngrue/.conda-envs/rev/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ngrue/.conda-envs/rev/lib/python3.8/site-packages/reV/econ/cli_econ.py", line 309, in local
    Econ.reV_run(points=points,
  File "/home/ngrue/.conda-envs/rev/lib/python3.8/site-packages/reV/econ/econ.py", line 436, in reV_run
    econ = cls(pc, cf_file,
  File "/home/ngrue/.conda-envs/rev/lib/python3.8/site-packages/reV/econ/econ.py", line 99, in __init__
    self._init_h5(mode=mode)
  File "/home/ngrue/.conda-envs/rev/lib/python3.8/site-packages/reV/generation/base.py", line 948, in _init_h5
    Outputs.init_h5(self._fpath, self.output_request, shapes, attrs,
  File "/home/ngrue/.conda-envs/rev/lib/python3.8/site-packages/reV/handlers/outputs.py", line 937, in init_h5
    logger.debug("\t- Configurations saved as attributes "
  File "/home/ngrue/.conda-envs/rev/lib/python3.8/site-packages/reV/handlers/outputs.py", line 924, in init_h5
    f['meta'] = meta
  File "/home/ngrue/.conda-envs/rev/lib/python3.8/site-packages/reV/handlers/outputs.py", line 197, in __setitem__
    self._set_meta(ds, arr)
  File "/home/ngrue/.conda-envs/rev/lib/python3.8/site-packages/reV/handlers/outputs.py", line 382, in _set_meta
    meta = to_records_array(meta)
  File "/home/ngrue/.conda-envs/rev/lib/python3.8/site-packages/rex/rechunk_h5/rechunk_h5.py", line 141, in to_records_array
    dtype = get_dtype(c_data)
  File "/home/ngrue/.conda-envs/rev/lib/python3.8/site-packages/rex/rechunk_h5/rechunk_h5.py", line 116, in get_dtype
    size = int(col.astype(str).str.len().max())
ValueError: cannot convert float NaN to integer
```

**To Reproduce**
error message from the log file at this location:
`/lustre/eaglefs/shared-projects/rev/projects/lcoe_maps/rev_v2/gen_01_benchmark/logs/stdout/econ_01_benchmark_econ_2019_03_5957123.e`

**Charge code**
SETP.10306.32.01.03

**Comment by nickwg03** [comment]
FYI, I haven't been able to pinpoint where the failure is or if it is user-error. When I run gen and then econ separately (i.e. running gen, then pointing econ to the cf_files generated from gen) it doesn't fail in the same way.

So I'd say hold off trying to tackle this since we have a way forward, but we might revisit after we get this initial push out the door.

**Comment by MRossol** [comment]
@nickwg03  sounds good, still super weird...
